name: Auto Merge QA to Master

on:
  pull_request:
    types: [opened]
    branches:
      - master

jobs:
  auto-merge:
    if: github.event.pull_request.head.ref == 'qa'
    runs-on: ubuntu-latest

    steps:
      - name: Auto merge PR
        run: gh pr merge "${{ github.event.pull_request.number }}" --repo "${{ github.repository }}" --auto --squash
        env:
          GH_TOKEN: ${{ github.token }}
