name: Auto Merge QA to Master

on:
  pull_request:
    types: [opened]
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: github.event.pull_request.head.ref == 'qa'
    runs-on: ubuntu-latest

    steps:
      - name: Enable auto-merge
        
        run: |
          gh pr merge 7b7385b7ac118644b711f81459c0820de66814b0  \
            --repo "vidyasrinivas7890/Learning" \
            --auto \
            --squash
